import { makeBannerImage } from "@/lib/banner-utils";
import type { Banner, MediaAsset } from "@/types/banner";

function img(title: string, subtitle: string, from: string, to: string, mobile = false) {
  return makeBannerImage({
    title,
    subtitle,
    from,
    to,
    width: mobile ? 800 : 1600,
    height: mobile ? 600 : 500,
  });
}

export const banners: Banner[] = [
  {
    id: "BNR-1001",
    name: "Monsoon Fuel Offer",
    campaignName: "Monsoon Procurement 2026",
    description: "Seasonal diesel and furnace oil pricing for industrial buyers during monsoon demand.",
    campaignType: "PROMOTIONAL",
    platforms: ["CUSTOMER_APP"],
    placements: ["HOME_HERO"],
    desktopImage: img("Monsoon Fuel Offer", "Seasonal rates on bulk ULSD", "#0B4F8A", "#1D4ED8"),
    mobileImage: img("Monsoon Fuel Offer", "Seasonal rates on bulk ULSD", "#0B4F8A", "#1D4ED8", true),
    desktopMediaId: "MED-1001",
    mobileMediaId: "MED-1002",
    headline: "Monsoon Fuel Offer",
    subheadline: "Lock in seasonal bulk rates before depot tightness.",
    ctaText: "Explore Offers",
    ctaAction: "OPEN_OFFER",
    targetId: "OFF-7712",
    startDate: "2026-08-15",
    startTime: "06:00",
    endDate: "2026-09-30",
    endTime: "23:59",
    timezone: "Asia/Kolkata",
    status: "ACTIVE",
    priority: 1,
    displayOrder: 10,
    audience: ["ALL_CUSTOMERS", "BUSINESS_CUSTOMERS"],
    impressions: 48210,
    clicks: 2144,
    ctr: 4.45,
    createdBy: "Admin",
    createdAt: "2026-08-10T11:20:00+05:30",
    updatedAt: "2026-09-01T09:10:00+05:30",
  },
  {
    id: "BNR-1002",
    name: "Bulk Order Savings",
    campaignName: "Q3 Volume Incentive",
    description: "Web marketplace banner for high-volume polymer buyers.",
    campaignType: "OFFER",
    platforms: ["CUSTOMER_WEB"],
    placements: ["MARKETPLACE"],
    desktopImage: img("Bulk Order Savings", "Better rates on 50 MT+", "#0F766E", "#115E59"),
    mobileImage: img("Bulk Order Savings", "Better rates on 50 MT+", "#0F766E", "#115E59", true),
    desktopMediaId: "MED-1003",
    mobileMediaId: "MED-1004",
    headline: "Special Bulk Fuel Pricing",
    subheadline: "Get better rates on bulk orders.",
    ctaText: "Open Marketplace",
    ctaAction: "OPEN_MARKETPLACE",
    startDate: "2026-09-20",
    startTime: "09:00",
    endDate: "2026-10-15",
    endTime: "23:59",
    timezone: "Asia/Kolkata",
    status: "SCHEDULED",
    priority: 2,
    displayOrder: 20,
    audience: ["HIGH_VALUE_CUSTOMERS", "BUSINESS_CUSTOMERS"],
    impressions: 0,
    clicks: 0,
    ctr: 0,
    createdBy: "Admin",
    createdAt: "2026-09-04T14:00:00+05:30",
    updatedAt: "2026-09-04T14:00:00+05:30",
  },
  {
    id: "BNR-1003",
    name: "Seller Offer Promotion",
    campaignName: "Seller Growth Push",
    description: "Encourage sellers to publish live offers from the mobile app.",
    campaignType: "PROMOTIONAL",
    platforms: ["SELLER_APP"],
    placements: ["SELLER_DASHBOARD"],
    desktopImage: img("Publish Live Offers", "Reach verified industrial buyers", "#1E3A5F", "#2563EB"),
    mobileImage: img("Publish Live Offers", "Reach verified industrial buyers", "#1E3A5F", "#2563EB", true),
    desktopMediaId: "MED-1005",
    mobileMediaId: "MED-1006",
    headline: "Promote Your Live Offers",
    subheadline: "Active offers get featured to high-intent buyers.",
    ctaText: "Go to My Offers",
    ctaAction: "OPEN_OFFER",
    targetId: "OFF-7712",
    startDate: "2026-09-01",
    startTime: "08:00",
    endDate: "2026-09-30",
    endTime: "22:00",
    timezone: "Asia/Kolkata",
    status: "ACTIVE",
    priority: 2,
    displayOrder: 12,
    audience: ["ALL_SELLERS", "SELLERS_WITH_ACTIVE_OFFERS"],
    impressions: 12840,
    clicks: 910,
    ctr: 7.09,
    createdBy: "Admin",
    createdAt: "2026-08-28T10:15:00+05:30",
    updatedAt: "2026-09-02T08:40:00+05:30",
  },
  {
    id: "BNR-1004",
    name: "Complete Your KYC",
    campaignName: "Seller Compliance Drive",
    description: "Compliance nudge for sellers with incomplete KYC on Seller Web.",
    campaignType: "ANNOUNCEMENT",
    platforms: ["SELLER_WEB"],
    placements: ["SELLER_DASHBOARD"],
    desktopImage: img("Complete Your KYC", "Unlock payouts and live offers", "#9A3412", "#C2410C"),
    mobileImage: img("Complete Your KYC", "Unlock payouts and live offers", "#9A3412", "#C2410C", true),
    desktopMediaId: "MED-1007",
    mobileMediaId: "MED-1008",
    headline: "Complete Your KYC",
    subheadline: "Verified sellers get faster settlement and higher visibility.",
    ctaText: "Open Documents",
    ctaAction: "NO_ACTION",
    startDate: "2026-08-01",
    startTime: "00:00",
    endDate: "2026-12-31",
    endTime: "23:59",
    timezone: "Asia/Kolkata",
    status: "ACTIVE",
    priority: 1,
    displayOrder: 8,
    audience: ["NEW_SELLERS", "VERIFIED_SELLERS"],
    impressions: 9640,
    clicks: 1288,
    ctr: 13.36,
    createdBy: "Neha Kapoor",
    createdAt: "2026-07-28T16:00:00+05:30",
    updatedAt: "2026-09-03T11:22:00+05:30",
  },
  {
    id: "BNR-1005",
    name: "New Procurement Opportunities",
    campaignName: "Seller Demand Alert",
    description: "Draft campaign for matching sellers to open procurement requests.",
    campaignType: "INFORMATIONAL",
    platforms: ["SELLER_APP", "SELLER_WEB"],
    placements: ["SELLER_DASHBOARD", "SELLER_MARKETPLACE"],
    desktopImage: img("New Demand Live", "Quote on open procurement", "#312E81", "#4338CA"),
    mobileImage: img("New Demand Live", "Quote on open procurement", "#312E81", "#4338CA", true),
    desktopMediaId: "MED-1009",
    mobileMediaId: "MED-1010",
    headline: "New Procurement Opportunities",
    subheadline: "Open RFQs matching your grades are waiting.",
    ctaText: "View Marketplace",
    ctaAction: "OPEN_MARKETPLACE",
    startDate: "2026-09-12",
    startTime: "09:00",
    endDate: "2026-09-26",
    endTime: "21:00",
    timezone: "Asia/Kolkata",
    status: "DRAFT",
    priority: 3,
    displayOrder: 40,
    audience: ["VERIFIED_SELLERS", "HIGH_PERFORMING_SELLERS"],
    impressions: 0,
    clicks: 0,
    ctr: 0,
    createdBy: "Admin",
    createdAt: "2026-09-06T12:30:00+05:30",
    updatedAt: "2026-09-06T12:30:00+05:30",
  },
  {
    id: "BNR-1006",
    name: "Diwali Fuel Offer",
    campaignName: "Festival Campaign",
    description: "Customer home hero for Diwali bulk fuel booking window.",
    campaignType: "FESTIVAL",
    platforms: ["CUSTOMER_APP", "CUSTOMER_WEB"],
    placements: ["HOME_HERO", "OFFERS"],
    desktopImage: img("Diwali Fuel Offer", "Book festive bulk volumes now", "#7C2D12", "#B45309"),
    mobileImage: img("Diwali Fuel Offer", "Book festive bulk volumes now", "#7C2D12", "#B45309", true),
    desktopMediaId: "MED-1011",
    mobileMediaId: "MED-1012",
    headline: "Diwali Fuel Offer",
    subheadline: "Festive window pricing on ULSD and furnace oil.",
    ctaText: "Explore Offers",
    ctaAction: "OPEN_OFFER",
    targetId: "OFF-7712",
    startDate: "2026-10-01",
    startTime: "00:00",
    endDate: "2026-10-31",
    endTime: "23:59",
    timezone: "Asia/Kolkata",
    status: "SCHEDULED",
    priority: 1,
    displayOrder: 5,
    audience: ["ALL_CUSTOMERS"],
    impressions: 0,
    clicks: 0,
    ctr: 0,
    createdBy: "Admin",
    createdAt: "2026-09-05T18:40:00+05:30",
    updatedAt: "2026-09-05T18:40:00+05:30",
  },
  {
    id: "BNR-1007",
    name: "PP Raffia Spotlight",
    campaignName: "Polymer Catalog Push",
    description: "Product listing banner highlighting PP Raffia availability.",
    campaignType: "PRODUCT",
    platforms: ["CUSTOMER_WEB"],
    placements: ["PRODUCT_LISTING", "PRODUCT_DETAIL"],
    desktopImage: img("PP Raffia Ready", "Hazira lots available this week", "#1E40AF", "#0EA5E9"),
    mobileImage: img("PP Raffia Ready", "Hazira lots available this week", "#1E40AF", "#0EA5E9", true),
    desktopMediaId: "MED-1013",
    mobileMediaId: "MED-1014",
    headline: "PP Raffia in Stock",
    subheadline: "Reliance Relene lots with active seller coverage.",
    ctaText: "View Product",
    ctaAction: "OPEN_PRODUCT",
    targetId: "GRD-1002",
    startDate: "2026-09-03",
    startTime: "08:00",
    endDate: "2026-09-21",
    endTime: "23:59",
    timezone: "Asia/Kolkata",
    status: "ACTIVE",
    priority: 3,
    displayOrder: 18,
    audience: ["EXISTING_CUSTOMERS", "BUSINESS_CUSTOMERS"],
    impressions: 22110,
    clicks: 980,
    ctr: 4.43,
    createdBy: "Admin",
    createdAt: "2026-09-02T09:05:00+05:30",
    updatedAt: "2026-09-05T10:12:00+05:30",
  },
  {
    id: "BNR-1008",
    name: "Settlement Reminder",
    campaignName: "Seller Finance Nudge",
    description: "Paused while finance copy is revised.",
    campaignType: "INFORMATIONAL",
    platforms: ["SELLER_WEB"],
    placements: ["SETTLEMENT"],
    desktopImage: img("Settlement Window", "Submit invoices before cut-off", "#334155", "#0F172A"),
    mobileImage: img("Settlement Window", "Submit invoices before cut-off", "#334155", "#0F172A", true),
    desktopMediaId: "MED-1015",
    mobileMediaId: "MED-1016",
    headline: "Submit Invoices Before Cut-off",
    subheadline: "Weekly settlement closes every Thursday 18:00 IST.",
    ctaText: "Open Settlement",
    ctaAction: "NO_ACTION",
    startDate: "2026-09-01",
    startTime: "09:00",
    endDate: "2026-09-30",
    endTime: "18:00",
    timezone: "Asia/Kolkata",
    status: "PAUSED",
    priority: 4,
    displayOrder: 50,
    audience: ["ALL_SELLERS"],
    impressions: 4100,
    clicks: 188,
    ctr: 4.59,
    createdBy: "Amit Desai",
    createdAt: "2026-08-30T15:10:00+05:30",
    updatedAt: "2026-09-06T17:00:00+05:30",
  },
  {
    id: "BNR-1009",
    name: "Independence Day Campaign",
    campaignName: "August National Offer",
    description: "Expired festive campaign retained for reporting.",
    campaignType: "FESTIVAL",
    platforms: ["CUSTOMER_APP", "CUSTOMER_WEB"],
    placements: ["HOME_PROMOTIONAL", "OFFERS"],
    desktopImage: img("15 Aug Offer", "National day bulk booking window", "#14532D", "#166534"),
    mobileImage: img("15 Aug Offer", "National day bulk booking window", "#14532D", "#166534", true),
    desktopMediaId: "MED-1017",
    mobileMediaId: "MED-1018",
    headline: "Independence Day Bulk Booking",
    subheadline: "Limited window on furnace oil and ULSD.",
    ctaText: "View Offers",
    ctaAction: "OPEN_OFFER",
    targetId: "OFF-7712",
    startDate: "2026-08-10",
    startTime: "00:00",
    endDate: "2026-08-18",
    endTime: "23:59",
    timezone: "Asia/Kolkata",
    status: "EXPIRED",
    priority: 2,
    displayOrder: 30,
    audience: ["ALL_CUSTOMERS"],
    impressions: 67320,
    clicks: 3011,
    ctr: 4.47,
    createdBy: "Admin",
    createdAt: "2026-08-04T11:00:00+05:30",
    updatedAt: "2026-08-18T23:59:00+05:30",
  },
  {
    id: "BNR-1010",
    name: "Login Welcome",
    campaignName: "Customer Onboarding",
    description: "Login-screen welcome for returning buyers.",
    campaignType: "INFORMATIONAL",
    platforms: ["CUSTOMER_APP"],
    placements: ["LOGIN"],
    desktopImage: img("Welcome Back", "Industrial procurement in one OS", "#0B1220", "#1D4ED8"),
    mobileImage: img("Welcome Back", "Industrial procurement in one OS", "#0B1220", "#1D4ED8", true),
    desktopMediaId: "MED-1019",
    mobileMediaId: "MED-1020",
    headline: "Welcome back to PetroTrade",
    subheadline: "Track orders, offers and credit from one place.",
    ctaText: "Continue",
    ctaAction: "NO_ACTION",
    startDate: "2026-07-01",
    startTime: "00:00",
    endDate: "2026-12-31",
    endTime: "23:59",
    timezone: "Asia/Kolkata",
    status: "ACTIVE",
    priority: 5,
    displayOrder: 90,
    audience: ["EXISTING_CUSTOMERS"],
    impressions: 15420,
    clicks: 220,
    ctr: 1.43,
    createdBy: "Admin",
    createdAt: "2026-06-28T09:00:00+05:30",
    updatedAt: "2026-07-01T08:00:00+05:30",
  },
  {
    id: "BNR-1011",
    name: "High Value Buyer Program",
    campaignName: "Enterprise Accounts",
    description: "Home promotional strip for high-value customer web users.",
    campaignType: "PROMOTIONAL",
    platforms: ["CUSTOMER_WEB"],
    placements: ["HOME_PROMOTIONAL"],
    desktopImage: img("Enterprise Program", "Priority allocation and credit cover", "#0F172A", "#1E3A8A"),
    mobileImage: img("Enterprise Program", "Priority allocation and credit cover", "#0F172A", "#1E3A8A", true),
    desktopMediaId: "MED-1021",
    mobileMediaId: "MED-1022",
    headline: "High Value Buyer Program",
    subheadline: "Priority lots, dedicated ops and credit insurance.",
    ctaText: "Talk to Ops",
    ctaAction: "OPEN_ORDERS",
    startDate: "2026-09-01",
    startTime: "00:00",
    endDate: "2026-11-30",
    endTime: "23:59",
    timezone: "Asia/Kolkata",
    status: "ACTIVE",
    priority: 2,
    displayOrder: 14,
    audience: ["HIGH_VALUE_CUSTOMERS"],
    impressions: 8120,
    clicks: 640,
    ctr: 7.88,
    createdBy: "Admin",
    createdAt: "2026-08-25T13:45:00+05:30",
    updatedAt: "2026-09-01T10:00:00+05:30",
  },
  {
    id: "BNR-1012",
    name: "Dispatch SLA Banner",
    campaignName: "Seller Ops Excellence",
    description: "Scheduled reminder for on-time dispatch from Seller App.",
    campaignType: "ANNOUNCEMENT",
    platforms: ["SELLER_APP"],
    placements: ["DISPATCH"],
    desktopImage: img("On-time Dispatch", "Protect SLA and buyer trust", "#0E7490", "#155E75"),
    mobileImage: img("On-time Dispatch", "Protect SLA and buyer trust", "#0E7490", "#155E75", true),
    desktopMediaId: "MED-1023",
    mobileMediaId: "MED-1024",
    headline: "Keep Dispatch Within SLA",
    subheadline: "Update vehicle and e-way details before cut-off.",
    ctaText: "Open Dispatch",
    ctaAction: "OPEN_ORDERS",
    startDate: "2026-09-10",
    startTime: "08:00",
    endDate: "2026-10-10",
    endTime: "20:00",
    timezone: "Asia/Kolkata",
    status: "SCHEDULED",
    priority: 3,
    displayOrder: 22,
    audience: ["HIGH_PERFORMING_SELLERS", "VERIFIED_SELLERS"],
    impressions: 0,
    clicks: 0,
    ctr: 0,
    createdBy: "Admin",
    createdAt: "2026-09-06T16:20:00+05:30",
    updatedAt: "2026-09-06T16:20:00+05:30",
  },
];

export const mediaAssets: MediaAsset[] = banners.flatMap((banner) => {
  const items: MediaAsset[] = [];
  if (banner.desktopImage && banner.desktopMediaId) {
    items.push({
      id: banner.desktopMediaId,
      fileName: `${slug(banner.name)}-desktop.svg`,
      type: "IMAGE",
      mimeType: "image/svg+xml",
      url: banner.desktopImage,
      width: 1600,
      height: 500,
      usedIn: [banner.name],
      uploadedAt: banner.createdAt,
      uploadedBy: banner.createdBy,
    });
  }
  if (banner.mobileImage && banner.mobileMediaId) {
    items.push({
      id: banner.mobileMediaId,
      fileName: `${slug(banner.name)}-mobile.svg`,
      type: "IMAGE",
      mimeType: "image/svg+xml",
      url: banner.mobileImage,
      width: 800,
      height: 600,
      usedIn: [banner.name],
      uploadedAt: banner.createdAt,
      uploadedBy: banner.createdBy,
    });
  }
  return items;
});

function slug(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}
