import type { Dispute } from "@/types";

export const disputes: Dispute[] = [
  {
    id: "DSP-204",
    orderId: "PT-8974",
    customer: "Delta Packaging Mills",
    seller: "Desert Sands Crude",
    category: "Delivery",
    amount: 24480000,
    priority: "Critical",
    status: "Investigating",
    createdAt: "2026-08-26T21:10:00+05:30",
    assignedTo: "Neha Kapoor",
  },
  {
    id: "DSP-198",
    orderId: "PT-9004",
    customer: "Eastern Pipe Works",
    seller: "Hygain Commodities",
    category: "Quality",
    amount: 2428800,
    priority: "High",
    status: "Awaiting Info",
    createdAt: "2026-09-04T10:40:00+05:30",
    assignedTo: "Unassigned",
  },
  {
    id: "DSP-191",
    orderId: "PT-8980",
    customer: "Sierra Films",
    seller: "SkyHigh Logistics",
    category: "Payment",
    amount: 1299600,
    priority: "Medium",
    status: "Open",
    createdAt: "2026-08-27T09:15:00+05:30",
    assignedTo: "Amit Desai",
  },
  {
    id: "DSP-176",
    orderId: "PT-8992",
    customer: "Apex Polymers Pvt Ltd",
    seller: "Oriental Polymers",
    category: "Quantity",
    amount: 98000,
    priority: "Low",
    status: "Resolved",
    createdAt: "2026-08-31T14:00:00+05:30",
    assignedTo: "Neha Kapoor",
  },
  {
    id: "DSP-169",
    orderId: "PT-8966",
    customer: "Eastern Pipe Works",
    seller: "Oriental Polymers",
    category: "Documentation",
    amount: 0,
    priority: "Medium",
    status: "Rejected",
    createdAt: "2026-09-04T15:22:00+05:30",
    assignedTo: "Support Desk",
  },
];
