import type { Grade, GradeCategory, GradeUsage } from "@/types/grade";

export const GRADE_CATEGORIES: GradeCategory[] = [
  { id: "cat-hdpe", code: "HDPE", name: "HDPE", parentGroup: "Polymers", description: "High-density polyethylene" },
  { id: "cat-ldpe", code: "LDPE", name: "LDPE", parentGroup: "Polymers", description: "Low-density polyethylene" },
  { id: "cat-lldpe", code: "LLDPE", name: "LLDPE", parentGroup: "Polymers", description: "Linear low-density polyethylene" },
  { id: "cat-pp", code: "PP", name: "PP", parentGroup: "Polymers", description: "Polypropylene" },
  { id: "cat-pet", code: "PET", name: "PET", parentGroup: "Polymers", description: "Polyethylene terephthalate" },
  { id: "cat-pvc", code: "PVC", name: "PVC", parentGroup: "Polymers", description: "Polyvinyl chloride" },
  { id: "cat-abs", code: "ABS", name: "ABS", parentGroup: "Polymers", description: "Acrylonitrile butadiene styrene" },
  { id: "cat-hips", code: "HIPS", name: "HIPS", parentGroup: "Polymers", description: "High-impact polystyrene" },
  { id: "cat-nylon", code: "NYLON", name: "Nylon", parentGroup: "Polymers", description: "Polyamide (PA6 / PA66)" },
  { id: "cat-eva", code: "EVA", name: "EVA", parentGroup: "Polymers", description: "Ethylene-vinyl acetate" },
  { id: "cat-pom", code: "POM", name: "POM", parentGroup: "Polymers", description: "Polyoxymethylene" },
  { id: "cat-pc", code: "PC", name: "PC", parentGroup: "Polymers", description: "Polycarbonate" },
  { id: "cat-san", code: "SAN", name: "SAN", parentGroup: "Polymers", description: "Styrene acrylonitrile" },
  { id: "cat-gpps", code: "GPPS", name: "GPPS", parentGroup: "Polymers", description: "General purpose polystyrene" },
  { id: "cat-pmma", code: "PMMA", name: "PMMA", parentGroup: "Polymers", description: "Polymethyl methacrylate" },
  { id: "cat-pbt", code: "PBT", name: "PBT", parentGroup: "Polymers", description: "Polybutylene terephthalate" },
  { id: "cat-compounds", code: "COMPOUNDS", name: "Compounds", parentGroup: "Compounds" },
  { id: "cat-masterbatch", code: "MASTERBATCH", name: "Masterbatch", parentGroup: "Masterbatch" },
  { id: "cat-elastomer", code: "ELASTOMER", name: "Elastomer", parentGroup: "Elastomers" },
  { id: "cat-chemicals", code: "CHEMICALS", name: "Chemicals", parentGroup: "Chemicals" },
  { id: "cat-solvents", code: "SOLVENTS", name: "Solvents", parentGroup: "Solvents" },
  { id: "cat-intermediates", code: "INTERMEDIATES", name: "Intermediates", parentGroup: "Intermediates" },
  { id: "cat-recycled", code: "RECYCLED", name: "Recycled", parentGroup: "Recycled" },
  { id: "cat-base-oil", code: "BASE_OIL", name: "Base Oil", parentGroup: "Base Oils" },
  { id: "cat-specialty", code: "SPECIALTY", name: "Specialty", parentGroup: "Specialty" },
];

const used = (offers: number, prs: number, orders: number, invoices: number, shipments: number, reports: number): GradeUsage => ({
  marketplaceOffers: offers,
  purchaseRequests: prs,
  orders,
  invoices,
  shipments,
  reports,
});

const unused: GradeUsage = used(0, 0, 0, 0, 0, 0);

type Seed = Omit<Grade, "categoryName" | "applications" | "sortOrder"> & {
  applications?: string[];
  sortOrder?: number;
};

function hydrate(seeds: Seed[]): Grade[] {
  const categoryName = (categoryId: string) =>
    GRADE_CATEGORIES.find((item) => item.id === categoryId)?.name ?? categoryId;

  return seeds.map((seed, index) => ({
    ...seed,
    categoryName: categoryName(seed.categoryId),
    applications: seed.applications ?? [],
    sortOrder: seed.sortOrder ?? index + 1,
  }));
}

const seeds: Seed[] = [
  {
    id: "GRD-1001",
    gradeCode: "HDPE_FILM",
    gradeName: "HD Film",
    categoryId: "cat-hdpe",
    description: "High-density polyethylene film grade for liners and flexible packaging.",
    applications: ["Packaging", "Film", "Flexible Packaging"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-06-12T08:10:00.000Z",
    updatedAt: "2026-09-08T11:22:00.000Z",
    createdBy: "Priya Shah",
    updatedBy: "Admin",
    usage: used(14, 9, 22, 18, 16, 4),
  },
  {
    id: "GRD-1002",
    gradeCode: "HDPE_BLOW",
    gradeName: "HD Blow",
    categoryId: "cat-hdpe",
    description: "Blow moulding HDPE for drums, jerry cans and industrial containers.",
    applications: ["Blow Moulding", "Drums", "Containers"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-06-12T08:12:00.000Z",
    updatedAt: "2026-09-07T09:40:00.000Z",
    createdBy: "Priya Shah",
    updatedBy: "Priya Shah",
    usage: used(8, 5, 11, 9, 8, 2),
  },
  {
    id: "GRD-1003",
    gradeCode: "HDPE_PIPE",
    gradeName: "HD Pipe",
    categoryId: "cat-hdpe",
    description: "PE100 / pipe-grade HDPE for pressure piping and fittings.",
    applications: ["Pipes", "Fittings", "Infrastructure"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-06-14T10:00:00.000Z",
    updatedAt: "2026-09-04T14:18:00.000Z",
    createdBy: "Rahul Mehta",
    updatedBy: "Admin",
    usage: used(6, 4, 7, 6, 5, 2),
  },
  {
    id: "GRD-1004",
    gradeCode: "HDPE_MOULD",
    gradeName: "HD Mould",
    categoryId: "cat-hdpe",
    description: "Injection moulding HDPE for crates, caps and household items.",
    applications: ["Injection Moulding", "Crates", "Caps"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-06-15T09:20:00.000Z",
    updatedAt: "2026-09-02T16:05:00.000Z",
    createdBy: "Rahul Mehta",
    updatedBy: "Rahul Mehta",
    usage: used(5, 3, 6, 5, 4, 1),
  },
  {
    id: "GRD-1005",
    gradeCode: "LDPE_FILM",
    gradeName: "LD Film",
    categoryId: "cat-ldpe",
    description: "Low-density polyethylene film grade for bags and lamination.",
    applications: ["Film", "Bags", "Lamination"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-06-16T07:40:00.000Z",
    updatedAt: "2026-09-06T12:11:00.000Z",
    createdBy: "Priya Shah",
    updatedBy: "Admin",
    usage: used(7, 4, 9, 7, 6, 2),
  },
  {
    id: "GRD-1006",
    gradeCode: "LDPE_INJECTION",
    gradeName: "LD Injection",
    categoryId: "cat-ldpe",
    description: "Injection moulding LDPE for lids, closures and flexible parts.",
    applications: ["Injection Moulding", "Closures"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: false,
    createdAt: "2026-06-18T11:00:00.000Z",
    updatedAt: "2026-08-28T10:30:00.000Z",
    createdBy: "Admin",
    updatedBy: "Admin",
    usage: used(2, 1, 1, 1, 0, 0),
  },
  {
    id: "GRD-1007",
    gradeCode: "LLDPE_FILM",
    gradeName: "LLDPE Film",
    categoryId: "cat-lldpe",
    description: "Linear low-density film grade for stretch wrap and agricultural film.",
    applications: ["Stretch Wrap", "Agricultural Film", "Pouches"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-06-19T08:30:00.000Z",
    updatedAt: "2026-09-09T08:15:00.000Z",
    createdBy: "Priya Shah",
    updatedBy: "Priya Shah",
    usage: used(11, 6, 15, 12, 10, 3),
  },
  {
    id: "GRD-1008",
    gradeCode: "LLDPE_ROTO",
    gradeName: "LLDPE Rotomoulding",
    categoryId: "cat-lldpe",
    description: "Rotomoulding LLDPE for tanks and large hollow articles.",
    applications: ["Rotomoulding", "Tanks"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-06-20T09:00:00.000Z",
    updatedAt: "2026-08-30T13:20:00.000Z",
    createdBy: "Rahul Mehta",
    updatedBy: "Rahul Mehta",
    usage: used(3, 2, 3, 2, 2, 1),
  },
  {
    id: "GRD-1009",
    gradeCode: "PP_RAFFIA",
    gradeName: "PP Raffia",
    categoryId: "cat-pp",
    description: "Raffia / woven-sack polypropylene, typically 3.5 MFI.",
    applications: ["Woven Sacks", "Raffia", "FIBC"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-06-08T06:50:00.000Z",
    updatedAt: "2026-09-09T15:40:00.000Z",
    createdBy: "Priya Shah",
    updatedBy: "Admin",
    usage: used(18, 12, 28, 24, 20, 5),
  },
  {
    id: "GRD-1010",
    gradeCode: "PP_FILM",
    gradeName: "PP Film",
    categoryId: "cat-pp",
    description: "Oriented / TQ film polypropylene for packaging films.",
    applications: ["Film", "Packaging"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-06-09T07:10:00.000Z",
    updatedAt: "2026-09-05T10:05:00.000Z",
    createdBy: "Priya Shah",
    updatedBy: "Priya Shah",
    usage: used(9, 5, 12, 10, 8, 2),
  },
  {
    id: "GRD-1011",
    gradeCode: "PP_INJECTION",
    gradeName: "PP Injection",
    categoryId: "cat-pp",
    description: "Homopolymer injection grade for thin-wall moulding and housewares.",
    applications: ["Injection Moulding", "Housewares", "Packaging"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-06-10T08:00:00.000Z",
    updatedAt: "2026-09-08T17:12:00.000Z",
    createdBy: "Rahul Mehta",
    updatedBy: "Admin",
    usage: used(10, 7, 14, 11, 9, 3),
  },
  {
    id: "GRD-1012",
    gradeCode: "PP_RANDOM",
    gradeName: "PP Random",
    categoryId: "cat-pp",
    description: "Random copolymer PP for transparent containers and blow moulding.",
    applications: ["Blow Moulding", "Transparent Containers"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-06-11T09:15:00.000Z",
    updatedAt: "2026-09-01T11:45:00.000Z",
    createdBy: "Admin",
    updatedBy: "Admin",
    usage: used(4, 3, 5, 4, 3, 1),
  },
  {
    id: "GRD-1013",
    gradeCode: "PP_CP",
    gradeName: "PP CP",
    categoryId: "cat-pp",
    description: "Impact copolymer polypropylene for automotive and industrial parts.",
    applications: ["Automotive", "Industrial Parts"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-06-21T10:20:00.000Z",
    updatedAt: "2026-08-27T09:00:00.000Z",
    createdBy: "Rahul Mehta",
    updatedBy: "Rahul Mehta",
    usage: used(5, 2, 4, 3, 3, 1),
  },
  {
    id: "GRD-1014",
    gradeCode: "PP_UNFILLED",
    gradeName: "PP Unfilled",
    categoryId: "cat-pp",
    description: "Unfilled polypropylene compound base for further compounding.",
    applications: ["Compounding", "Injection Moulding"],
    status: "ACTIVE",
    customerVisible: false,
    sellerVisible: true,
    createdAt: "2026-06-22T12:00:00.000Z",
    updatedAt: "2026-08-20T14:00:00.000Z",
    createdBy: "Admin",
    updatedBy: "Admin",
    usage: used(1, 0, 0, 0, 0, 0),
  },
  {
    id: "GRD-1015",
    gradeCode: "PET_BOTTLE",
    gradeName: "PET Bottle",
    categoryId: "cat-pet",
    description: "Bottle-grade PET resin for CSD and water bottles.",
    applications: ["Bottles", "Packaging"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-06-13T08:40:00.000Z",
    updatedAt: "2026-09-07T18:20:00.000Z",
    createdBy: "Priya Shah",
    updatedBy: "Priya Shah",
    usage: used(12, 8, 16, 14, 12, 3),
  },
  {
    id: "GRD-1016",
    gradeCode: "PET_SHEET",
    gradeName: "PET Sheet",
    categoryId: "cat-pet",
    description: "Sheet-grade PET for thermoforming and packaging trays.",
    applications: ["Sheet", "Thermoforming"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-06-24T07:55:00.000Z",
    updatedAt: "2026-08-31T08:10:00.000Z",
    createdBy: "Rahul Mehta",
    updatedBy: "Admin",
    usage: used(3, 2, 2, 2, 1, 1),
  },
  {
    id: "GRD-1017",
    gradeCode: "PVC_PIPE",
    gradeName: "PVC Pipe",
    categoryId: "cat-pvc",
    description: "Suspension PVC (K67) for pipes, fittings and rigid profiles.",
    applications: ["Pipes", "Fittings", "Rigid Profiles"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-06-07T06:30:00.000Z",
    updatedAt: "2026-09-08T09:50:00.000Z",
    createdBy: "Priya Shah",
    updatedBy: "Admin",
    usage: used(13, 9, 19, 16, 14, 4),
  },
  {
    id: "GRD-1018",
    gradeCode: "RPVC",
    gradeName: "RPVC",
    categoryId: "cat-pvc",
    description: "Rigid PVC compound for profiles, window frames and sheets.",
    applications: ["Profiles", "Windows", "Sheets"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-06-25T10:10:00.000Z",
    updatedAt: "2026-09-03T12:40:00.000Z",
    createdBy: "Admin",
    updatedBy: "Admin",
    usage: used(4, 2, 3, 3, 2, 1),
  },
  {
    id: "GRD-1019",
    gradeCode: "ABS_INJECTION",
    gradeName: "ABS Injection",
    categoryId: "cat-abs",
    description: "General-purpose ABS for automotive interiors and appliances.",
    applications: ["Automotive", "Appliances", "Injection Moulding"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-06-26T11:25:00.000Z",
    updatedAt: "2026-09-06T16:30:00.000Z",
    createdBy: "Rahul Mehta",
    updatedBy: "Rahul Mehta",
    usage: used(6, 4, 8, 6, 5, 2),
  },
  {
    id: "GRD-1020",
    gradeCode: "G_ABS",
    gradeName: "gABS",
    categoryId: "cat-abs",
    description: "General-purpose ABS reprocessed / gABS for non-critical moulding.",
    applications: ["Injection Moulding", "Compounds"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-06-27T09:00:00.000Z",
    updatedAt: "2026-08-25T11:20:00.000Z",
    createdBy: "Admin",
    updatedBy: "Admin",
    usage: used(2, 1, 2, 1, 1, 0),
  },
  {
    id: "GRD-1021",
    gradeCode: "ABS_REGRIND_IMPORTED",
    gradeName: "Imported ABS Regrind",
    categoryId: "cat-abs",
    description: "Imported ABS regrind for blending and non-food applications.",
    applications: ["Regrind", "Blending"],
    status: "ACTIVE",
    customerVisible: false,
    sellerVisible: true,
    createdAt: "2026-06-28T13:40:00.000Z",
    updatedAt: "2026-08-19T15:00:00.000Z",
    createdBy: "Priya Shah",
    updatedBy: "Priya Shah",
    usage: used(1, 1, 0, 0, 0, 0),
  },
  {
    id: "GRD-1022",
    gradeCode: "HIPS_INJECTION",
    gradeName: "HIPS",
    categoryId: "cat-hips",
    description: "High-impact polystyrene for packaging and appliance housings.",
    applications: ["Packaging", "Appliances"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-06-29T08:05:00.000Z",
    updatedAt: "2026-09-01T09:25:00.000Z",
    createdBy: "Rahul Mehta",
    updatedBy: "Admin",
    usage: used(3, 2, 4, 3, 2, 1),
  },
  {
    id: "GRD-1023",
    gradeCode: "PA66_GF30_FR_BK",
    gradeName: "PA66 30% GF FR BK",
    categoryId: "cat-nylon",
    description: "Glass-filled flame-retardant black PA66 for electrical housings.",
    applications: ["Electrical", "Automotive", "Engineering Plastics"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-07-01T10:00:00.000Z",
    updatedAt: "2026-09-04T08:55:00.000Z",
    createdBy: "Priya Shah",
    updatedBy: "Priya Shah",
    usage: used(4, 3, 5, 4, 3, 1),
  },
  {
    id: "GRD-1024",
    gradeCode: "NYLON_PA6",
    gradeName: "Nylon PA6",
    categoryId: "cat-nylon",
    description: "Unfilled polyamide 6 for engineering and textile applications.",
    applications: ["Engineering Plastics", "Textiles"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-07-02T09:30:00.000Z",
    updatedAt: "2026-08-29T10:10:00.000Z",
    createdBy: "Admin",
    updatedBy: "Admin",
    usage: used(2, 1, 2, 2, 1, 1),
  },
  {
    id: "GRD-1025",
    gradeCode: "EVA_FILM",
    gradeName: "EVA",
    categoryId: "cat-eva",
    description: "EVA copolymer for film, foam and hot-melt applications.",
    applications: ["Film", "Foam", "Adhesives"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-07-03T07:45:00.000Z",
    updatedAt: "2026-09-02T13:00:00.000Z",
    createdBy: "Rahul Mehta",
    updatedBy: "Rahul Mehta",
    usage: used(3, 2, 3, 2, 2, 1),
  },
  {
    id: "GRD-1026",
    gradeCode: "POM_COPOLYMER",
    gradeName: "POM",
    categoryId: "cat-pom",
    description: "Acetal copolymer for precision gears and mechanical parts.",
    applications: ["Gears", "Precision Parts"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-07-04T11:15:00.000Z",
    updatedAt: "2026-08-26T16:40:00.000Z",
    createdBy: "Priya Shah",
    updatedBy: "Admin",
    usage: used(2, 1, 1, 1, 1, 0),
  },
  {
    id: "GRD-1027",
    gradeCode: "PC_INJECTION",
    gradeName: "PC",
    categoryId: "cat-pc",
    description: "Polycarbonate for transparent housings and electrical parts.",
    applications: ["Electrical", "Transparent Parts"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-07-05T08:20:00.000Z",
    updatedAt: "2026-09-03T07:30:00.000Z",
    createdBy: "Admin",
    updatedBy: "Admin",
    usage: used(3, 2, 3, 2, 2, 1),
  },
  {
    id: "GRD-1028",
    gradeCode: "SAN_TRANSPARENT",
    gradeName: "SAN",
    categoryId: "cat-san",
    description: "Styrene acrylonitrile for transparent housewares and cosmetics packaging.",
    applications: ["Housewares", "Packaging"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-07-06T09:50:00.000Z",
    updatedAt: "2026-08-22T12:15:00.000Z",
    createdBy: "Rahul Mehta",
    updatedBy: "Rahul Mehta",
    usage: used(1, 1, 1, 1, 0, 0),
  },
  {
    id: "GRD-1029",
    gradeCode: "GPPS_GENERAL",
    gradeName: "GPPS",
    categoryId: "cat-gpps",
    description: "General-purpose polystyrene for packaging and disposable items.",
    applications: ["Packaging", "Disposables"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-07-07T10:05:00.000Z",
    updatedAt: "2026-09-01T14:22:00.000Z",
    createdBy: "Priya Shah",
    updatedBy: "Priya Shah",
    usage: used(2, 1, 2, 2, 1, 1),
  },
  {
    id: "GRD-1030",
    gradeCode: "PMMA_SHEET",
    gradeName: "PMMA",
    categoryId: "cat-pmma",
    description: "Acrylic / PMMA for sheets, lighting and optical parts.",
    applications: ["Sheets", "Lighting", "Optical"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-07-08T08:00:00.000Z",
    updatedAt: "2026-08-24T09:40:00.000Z",
    createdBy: "Admin",
    updatedBy: "Admin",
    usage: used(1, 1, 1, 0, 0, 0),
  },
  {
    id: "GRD-1031",
    gradeCode: "PBT_GF",
    gradeName: "PBT",
    categoryId: "cat-pbt",
    description: "PBT engineering plastic for electrical connectors and automotive.",
    applications: ["Electrical", "Automotive"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-07-09T12:30:00.000Z",
    updatedAt: "2026-08-21T11:05:00.000Z",
    createdBy: "Rahul Mehta",
    updatedBy: "Admin",
    usage: used(1, 0, 1, 1, 0, 0),
  },
  {
    id: "GRD-1032",
    gradeCode: "PP_ABS",
    gradeName: "PP ABS",
    categoryId: "cat-compounds",
    description: "PP/ABS blend compound for automotive interior parts.",
    applications: ["Automotive", "Compounds"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-07-10T09:10:00.000Z",
    updatedAt: "2026-09-05T15:18:00.000Z",
    createdBy: "Priya Shah",
    updatedBy: "Priya Shah",
    usage: used(2, 1, 2, 1, 1, 0),
  },
  {
    id: "GRD-1033",
    gradeCode: "MASTERBATCH_BLACK",
    gradeName: "Masterbatch",
    categoryId: "cat-masterbatch",
    description: "Colour and additive masterbatches for polymer processing.",
    applications: ["Colouring", "Additives"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-07-11T07:20:00.000Z",
    updatedAt: "2026-09-06T10:00:00.000Z",
    createdBy: "Admin",
    updatedBy: "Admin",
    usage: used(5, 3, 6, 5, 4, 1),
  },
  {
    id: "GRD-1034",
    gradeCode: "TPU_ELASTOMER",
    gradeName: "TPU",
    categoryId: "cat-elastomer",
    description: "Thermoplastic polyurethane elastomer for hoses, films and footwear.",
    applications: ["Hoses", "Footwear", "Film"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-07-12T11:40:00.000Z",
    updatedAt: "2026-08-30T08:50:00.000Z",
    createdBy: "Rahul Mehta",
    updatedBy: "Rahul Mehta",
    usage: used(2, 1, 2, 1, 1, 0),
  },
  {
    id: "GRD-1035",
    gradeCode: "TPEE",
    gradeName: "TPEE",
    categoryId: "cat-elastomer",
    description: "Thermoplastic polyester elastomer for flexible engineering parts.",
    applications: ["Automotive", "Cable", "Elastomers"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-07-13T10:15:00.000Z",
    updatedAt: "2026-08-18T14:35:00.000Z",
    createdBy: "Priya Shah",
    updatedBy: "Admin",
    usage: used(1, 0, 1, 0, 0, 0),
  },
  {
    id: "GRD-1036",
    gradeCode: "TPV",
    gradeName: "TPV",
    categoryId: "cat-elastomer",
    description: "Thermoplastic vulcanizate for automotive weatherseals and soft-touch parts.",
    applications: ["Automotive", "Seals"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-07-14T09:00:00.000Z",
    updatedAt: "2026-08-17T09:20:00.000Z",
    createdBy: "Admin",
    updatedBy: "Admin",
    usage: used(1, 1, 0, 0, 0, 0),
  },
  {
    id: "GRD-1037",
    gradeCode: "PLASTOMER",
    gradeName: "Plastomer",
    categoryId: "cat-elastomer",
    description: "Polyolefin plastomer for film modification and impact improvement.",
    applications: ["Film Modification", "Impact Modifier"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: false,
    createdAt: "2026-07-15T08:25:00.000Z",
    updatedAt: "2026-08-16T12:00:00.000Z",
    createdBy: "Rahul Mehta",
    updatedBy: "Rahul Mehta",
    usage: unused,
  },
  {
    id: "GRD-1038",
    gradeCode: "METALLOCENE",
    gradeName: "Metallocene",
    categoryId: "cat-specialty",
    description: "Metallocene-catalyzed polyethylene for high-clarity film.",
    applications: ["Film", "Specialty Polymers"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-07-16T13:10:00.000Z",
    updatedAt: "2026-09-02T08:40:00.000Z",
    createdBy: "Priya Shah",
    updatedBy: "Priya Shah",
    usage: used(2, 1, 1, 1, 1, 0),
  },
  {
    id: "GRD-1039",
    gradeCode: "XLPE",
    gradeName: "XLPE",
    categoryId: "cat-specialty",
    description: "Cross-linkable polyethylene for cable insulation.",
    applications: ["Cable", "Insulation"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-07-17T07:50:00.000Z",
    updatedAt: "2026-08-15T10:25:00.000Z",
    createdBy: "Admin",
    updatedBy: "Admin",
    usage: used(1, 1, 1, 1, 1, 0),
  },
  {
    id: "GRD-1040",
    gradeCode: "EVOH",
    gradeName: "EVOH",
    categoryId: "cat-specialty",
    description: "Ethylene vinyl alcohol barrier resin for multilayer packaging.",
    applications: ["Barrier Film", "Packaging"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-07-18T11:00:00.000Z",
    updatedAt: "2026-08-14T16:10:00.000Z",
    createdBy: "Rahul Mehta",
    updatedBy: "Admin",
    usage: unused,
  },
  {
    id: "GRD-1041",
    gradeCode: "PBAT",
    gradeName: "PBAT",
    categoryId: "cat-specialty",
    description: "Biodegradable polyester for compostable film and bags.",
    applications: ["Compostable Film", "Bags"],
    status: "INACTIVE",
    customerVisible: false,
    sellerVisible: false,
    createdAt: "2026-07-19T09:35:00.000Z",
    updatedAt: "2026-08-12T09:00:00.000Z",
    createdBy: "Priya Shah",
    updatedBy: "Priya Shah",
    usage: unused,
  },
  {
    id: "GRD-1042",
    gradeCode: "ETHYL_ACETATE",
    gradeName: "Ethyl Acetate",
    categoryId: "cat-solvents",
    description: "Industrial ethyl acetate solvent for coatings, inks and adhesives.",
    applications: ["Coatings", "Inks", "Adhesives"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-07-20T08:15:00.000Z",
    updatedAt: "2026-09-07T11:05:00.000Z",
    createdBy: "Admin",
    updatedBy: "Admin",
    usage: used(6, 4, 7, 6, 5, 2),
  },
  {
    id: "GRD-1043",
    gradeCode: "ACETONE",
    gradeName: "Acetone",
    categoryId: "cat-solvents",
    description: "Industrial acetone for cleaning, coatings and chemical synthesis.",
    applications: ["Solvent", "Cleaning", "Synthesis"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-07-21T10:45:00.000Z",
    updatedAt: "2026-09-04T13:30:00.000Z",
    createdBy: "Rahul Mehta",
    updatedBy: "Rahul Mehta",
    usage: used(4, 3, 5, 4, 3, 1),
  },
  {
    id: "GRD-1044",
    gradeCode: "IPA",
    gradeName: "IPA",
    categoryId: "cat-solvents",
    description: "Isopropyl alcohol for pharma, electronics and industrial cleaning.",
    applications: ["Cleaning", "Pharma", "Electronics"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-07-22T07:00:00.000Z",
    updatedAt: "2026-09-08T08:20:00.000Z",
    createdBy: "Priya Shah",
    updatedBy: "Admin",
    usage: used(5, 3, 6, 5, 4, 1),
  },
  {
    id: "GRD-1045",
    gradeCode: "MEK",
    gradeName: "MEK",
    categoryId: "cat-solvents",
    description: "Methyl ethyl ketone for coatings, adhesives and degreasing.",
    applications: ["Coatings", "Adhesives"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-07-23T12:20:00.000Z",
    updatedAt: "2026-08-28T15:45:00.000Z",
    createdBy: "Admin",
    updatedBy: "Admin",
    usage: used(3, 2, 3, 2, 2, 1),
  },
  {
    id: "GRD-1046",
    gradeCode: "MIBK",
    gradeName: "MIBK",
    categoryId: "cat-solvents",
    description: "Methyl isobutyl ketone solvent for coatings and extraction.",
    applications: ["Coatings", "Extraction"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-07-24T09:40:00.000Z",
    updatedAt: "2026-08-27T10:15:00.000Z",
    createdBy: "Rahul Mehta",
    updatedBy: "Priya Shah",
    usage: used(2, 1, 2, 1, 1, 0),
  },
  {
    id: "GRD-1047",
    gradeCode: "BUTYL_ACETATE",
    gradeName: "Butyl Acetate",
    categoryId: "cat-solvents",
    description: "n-Butyl acetate for paints, coatings and flavour intermediates.",
    applications: ["Paints", "Coatings"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-07-25T08:55:00.000Z",
    updatedAt: "2026-09-03T09:10:00.000Z",
    createdBy: "Priya Shah",
    updatedBy: "Admin",
    usage: used(2, 1, 2, 2, 1, 0),
  },
  {
    id: "GRD-1048",
    gradeCode: "N_PROPYL_ACETATE",
    gradeName: "N-Propyl Acetate",
    categoryId: "cat-solvents",
    description: "n-Propyl acetate solvent for inks and coatings.",
    applications: ["Inks", "Coatings"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-07-26T11:05:00.000Z",
    updatedAt: "2026-08-23T08:30:00.000Z",
    createdBy: "Admin",
    updatedBy: "Admin",
    usage: unused,
  },
  {
    id: "GRD-1049",
    gradeCode: "CYCLOHEXANE",
    gradeName: "Cyclohexane",
    categoryId: "cat-solvents",
    description: "Cyclohexane for nylon intermediates and solvent applications.",
    applications: ["Intermediates", "Solvent"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-07-27T10:00:00.000Z",
    updatedAt: "2026-09-01T12:50:00.000Z",
    createdBy: "Rahul Mehta",
    updatedBy: "Rahul Mehta",
    usage: used(2, 2, 2, 1, 1, 1),
  },
  {
    id: "GRD-1050",
    gradeCode: "CYCLOHEXANONE",
    gradeName: "Cyclohexanone",
    categoryId: "cat-solvents",
    description: "Cyclohexanone for caprolactam, coatings and adhesives.",
    applications: ["Coatings", "Adhesives", "Intermediates"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-07-28T09:20:00.000Z",
    updatedAt: "2026-08-26T14:00:00.000Z",
    createdBy: "Priya Shah",
    updatedBy: "Admin",
    usage: used(1, 1, 1, 1, 0, 0),
  },
  {
    id: "GRD-1051",
    gradeCode: "ETHANOL",
    gradeName: "Ethanol",
    categoryId: "cat-solvents",
    description: "Industrial ethanol for solvents, sanitizers and chemical feedstock.",
    applications: ["Solvent", "Feedstock"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-07-29T07:40:00.000Z",
    updatedAt: "2026-09-06T07:55:00.000Z",
    createdBy: "Admin",
    updatedBy: "Admin",
    usage: used(3, 2, 4, 3, 2, 1),
  },
  {
    id: "GRD-1052",
    gradeCode: "IBA",
    gradeName: "IBA",
    categoryId: "cat-solvents",
    description: "Isobutanol for coatings, plasticizers and chemical intermediates.",
    applications: ["Coatings", "Plasticizers"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-07-30T13:00:00.000Z",
    updatedAt: "2026-08-20T11:40:00.000Z",
    createdBy: "Rahul Mehta",
    updatedBy: "Rahul Mehta",
    usage: unused,
  },
  {
    id: "GRD-1053",
    gradeCode: "CAUSTIC",
    gradeName: "Caustic",
    categoryId: "cat-chemicals",
    description: "Caustic soda (NaOH) for alumina, pulp, soap and chemical processing.",
    applications: ["Chemical Processing", "Pulp", "Soap"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-08-01T08:10:00.000Z",
    updatedAt: "2026-09-08T14:05:00.000Z",
    createdBy: "Priya Shah",
    updatedBy: "Admin",
    usage: used(7, 5, 9, 8, 6, 2),
  },
  {
    id: "GRD-1054",
    gradeCode: "TIO2",
    gradeName: "TiO2",
    categoryId: "cat-chemicals",
    description: "Titanium dioxide pigment for paints, plastics and masterbatch.",
    applications: ["Paints", "Plastics", "Masterbatch"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-08-02T09:25:00.000Z",
    updatedAt: "2026-09-05T16:40:00.000Z",
    createdBy: "Admin",
    updatedBy: "Admin",
    usage: used(4, 3, 5, 4, 3, 1),
  },
  {
    id: "GRD-1055",
    gradeCode: "MELAMINE",
    gradeName: "Melamine",
    categoryId: "cat-chemicals",
    description: "Melamine for laminates, resins and moulding compounds.",
    applications: ["Laminates", "Resins"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-08-03T10:50:00.000Z",
    updatedAt: "2026-08-29T09:15:00.000Z",
    createdBy: "Rahul Mehta",
    updatedBy: "Priya Shah",
    usage: used(2, 1, 2, 1, 1, 0),
  },
  {
    id: "GRD-1056",
    gradeCode: "GLYCERINE",
    gradeName: "Glycerine",
    categoryId: "cat-chemicals",
    description: "Refined glycerine for pharma, personal care and chemical synthesis.",
    applications: ["Pharma", "Personal Care"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-08-04T07:30:00.000Z",
    updatedAt: "2026-09-02T10:20:00.000Z",
    createdBy: "Priya Shah",
    updatedBy: "Admin",
    usage: used(2, 1, 2, 2, 1, 1),
  },
  {
    id: "GRD-1057",
    gradeCode: "POLYOL",
    gradeName: "Polyol",
    categoryId: "cat-chemicals",
    description: "Polyether polyol for polyurethane foams and elastomers.",
    applications: ["PU Foam", "Elastomers"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-08-05T11:10:00.000Z",
    updatedAt: "2026-08-31T13:25:00.000Z",
    createdBy: "Admin",
    updatedBy: "Admin",
    usage: used(3, 2, 3, 2, 2, 1),
  },
  {
    id: "GRD-1058",
    gradeCode: "ISOCYANATES",
    gradeName: "Isocyanates",
    categoryId: "cat-chemicals",
    description: "MDI / TDI isocyanates for polyurethane systems.",
    applications: ["PU Systems", "Foams"],
    status: "ACTIVE",
    customerVisible: false,
    sellerVisible: true,
    createdAt: "2026-08-06T08:45:00.000Z",
    updatedAt: "2026-08-22T15:00:00.000Z",
    createdBy: "Rahul Mehta",
    updatedBy: "Rahul Mehta",
    usage: used(1, 1, 1, 1, 0, 0),
  },
  {
    id: "GRD-1059",
    gradeCode: "PLASTICIZER",
    gradeName: "Plasticizer",
    categoryId: "cat-chemicals",
    description: "Phthalate / non-phthalate plasticizers for flexible PVC.",
    applications: ["Flexible PVC", "Cables"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-08-07T09:05:00.000Z",
    updatedAt: "2026-09-04T11:35:00.000Z",
    createdBy: "Priya Shah",
    updatedBy: "Admin",
    usage: used(3, 2, 4, 3, 2, 1),
  },
  {
    id: "GRD-1060",
    gradeCode: "SODIUM_HYDROSULPHITE",
    gradeName: "Sodium Hydrosulphite",
    categoryId: "cat-chemicals",
    description: "Sodium hydrosulphite for textile bleaching and vat dyeing.",
    applications: ["Textiles", "Bleaching"],
    status: "INACTIVE",
    customerVisible: false,
    sellerVisible: false,
    createdAt: "2026-08-08T12:00:00.000Z",
    updatedAt: "2026-08-18T08:40:00.000Z",
    createdBy: "Admin",
    updatedBy: "Admin",
    usage: unused,
  },
  {
    id: "GRD-1061",
    gradeCode: "ORTHO_XYLENE",
    gradeName: "Ortho Xylene",
    categoryId: "cat-intermediates",
    description: "o-Xylene feedstock for phthalic anhydride.",
    applications: ["Phthalic Anhydride", "Intermediates"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-08-09T10:20:00.000Z",
    updatedAt: "2026-09-03T08:00:00.000Z",
    createdBy: "Rahul Mehta",
    updatedBy: "Priya Shah",
    usage: used(2, 1, 2, 2, 1, 1),
  },
  {
    id: "GRD-1062",
    gradeCode: "STYRENE",
    gradeName: "Styrene",
    categoryId: "cat-intermediates",
    description: "Styrene monomer for PS, ABS and SBR production.",
    applications: ["PS", "ABS", "SBR"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-08-10T07:15:00.000Z",
    updatedAt: "2026-09-07T09:45:00.000Z",
    createdBy: "Priya Shah",
    updatedBy: "Admin",
    usage: used(4, 3, 5, 4, 3, 1),
  },
  {
    id: "GRD-1063",
    gradeCode: "MMA",
    gradeName: "MMA",
    categoryId: "cat-intermediates",
    description: "Methyl methacrylate monomer for PMMA and coatings.",
    applications: ["PMMA", "Coatings"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-08-11T11:30:00.000Z",
    updatedAt: "2026-08-28T12:10:00.000Z",
    createdBy: "Admin",
    updatedBy: "Admin",
    usage: used(1, 1, 1, 1, 1, 0),
  },
  {
    id: "GRD-1064",
    gradeCode: "C9",
    gradeName: "C-9",
    categoryId: "cat-intermediates",
    description: "C9 aromatic hydrocarbon for resins and solvents.",
    applications: ["Resins", "Solvents"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-08-12T08:50:00.000Z",
    updatedAt: "2026-08-25T10:05:00.000Z",
    createdBy: "Rahul Mehta",
    updatedBy: "Rahul Mehta",
    usage: used(1, 0, 1, 1, 0, 0),
  },
  {
    id: "GRD-1065",
    gradeCode: "AMINE",
    gradeName: "Amine",
    categoryId: "cat-intermediates",
    description: "Industrial amines for gas treating and chemical synthesis.",
    applications: ["Gas Treating", "Synthesis"],
    status: "ACTIVE",
    customerVisible: false,
    sellerVisible: true,
    createdAt: "2026-08-13T09:40:00.000Z",
    updatedAt: "2026-08-21T14:20:00.000Z",
    createdBy: "Priya Shah",
    updatedBy: "Admin",
    usage: unused,
  },
  {
    id: "GRD-1066",
    gradeCode: "PG",
    gradeName: "PG",
    categoryId: "cat-intermediates",
    description: "Propylene glycol for unsaturated polyester resins and antifreeze.",
    applications: ["Resins", "Antifreeze"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-08-14T10:10:00.000Z",
    updatedAt: "2026-09-01T11:00:00.000Z",
    createdBy: "Admin",
    updatedBy: "Admin",
    usage: used(2, 1, 2, 1, 1, 0),
  },
  {
    id: "GRD-1067",
    gradeCode: "DEG",
    gradeName: "DEG",
    categoryId: "cat-intermediates",
    description: "Diethylene glycol for resins, solvents and unsaturated polyesters.",
    applications: ["Resins", "Solvents"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-08-15T07:25:00.000Z",
    updatedAt: "2026-08-30T09:35:00.000Z",
    createdBy: "Rahul Mehta",
    updatedBy: "Priya Shah",
    usage: used(1, 1, 1, 1, 1, 0),
  },
  {
    id: "GRD-1068",
    gradeCode: "GLYCOL",
    gradeName: "Glycol",
    categoryId: "cat-intermediates",
    description: "Monoethylene glycol for polyester fibre and antifreeze.",
    applications: ["Polyester", "Antifreeze"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-08-16T12:45:00.000Z",
    updatedAt: "2026-09-05T08:15:00.000Z",
    createdBy: "Priya Shah",
    updatedBy: "Admin",
    usage: used(3, 2, 3, 3, 2, 1),
  },
  {
    id: "GRD-1069",
    gradeCode: "POLYBUTENE",
    gradeName: "Polybutene",
    categoryId: "cat-specialty",
    description: "Polybutene for adhesives, sealants and lubricant additives.",
    applications: ["Adhesives", "Lubricants"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-08-17T08:00:00.000Z",
    updatedAt: "2026-08-27T16:50:00.000Z",
    createdBy: "Admin",
    updatedBy: "Admin",
    usage: unused,
  },
  {
    id: "GRD-1070",
    gradeCode: "R_HDPE",
    gradeName: "rHDPE",
    categoryId: "cat-recycled",
    description: "Recycled HDPE for non-food moulding, pipes and crates.",
    applications: ["Recycled", "Moulding", "Pipes"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-08-18T09:30:00.000Z",
    updatedAt: "2026-09-08T10:40:00.000Z",
    createdBy: "Rahul Mehta",
    updatedBy: "Rahul Mehta",
    usage: used(5, 3, 6, 4, 4, 1),
  },
  {
    id: "GRD-1071",
    gradeCode: "R_LDPE",
    gradeName: "rLDPE",
    categoryId: "cat-recycled",
    description: "Recycled LDPE for films, liners and compounding.",
    applications: ["Recycled", "Film", "Compounding"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-08-19T10:20:00.000Z",
    updatedAt: "2026-09-06T12:25:00.000Z",
    createdBy: "Priya Shah",
    updatedBy: "Admin",
    usage: used(3, 2, 4, 3, 2, 1),
  },
  {
    id: "GRD-1072",
    gradeCode: "R_LLDPE",
    gradeName: "rLLDPE",
    categoryId: "cat-recycled",
    description: "Recycled LLDPE for film blending and non-food packaging.",
    applications: ["Recycled", "Film"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-08-20T11:00:00.000Z",
    updatedAt: "2026-09-02T15:10:00.000Z",
    createdBy: "Admin",
    updatedBy: "Admin",
    usage: used(2, 1, 2, 1, 1, 0),
  },
  {
    id: "GRD-1073",
    gradeCode: "R_PP",
    gradeName: "rPP",
    categoryId: "cat-recycled",
    description: "Recycled polypropylene for injection moulding and compounding.",
    applications: ["Recycled", "Injection Moulding"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-08-21T08:40:00.000Z",
    updatedAt: "2026-09-07T13:00:00.000Z",
    createdBy: "Rahul Mehta",
    updatedBy: "Priya Shah",
    usage: used(4, 2, 5, 4, 3, 1),
  },
  {
    id: "GRD-1074",
    gradeCode: "R_PP_UNFILLED",
    gradeName: "rPP Unfilled",
    categoryId: "cat-recycled",
    description: "Unfilled recycled PP for natural-colour compounding.",
    applications: ["Recycled", "Compounding"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-08-22T09:15:00.000Z",
    updatedAt: "2026-08-31T10:50:00.000Z",
    createdBy: "Priya Shah",
    updatedBy: "Admin",
    usage: used(1, 1, 1, 0, 0, 0),
  },
  {
    id: "GRD-1075",
    gradeCode: "R_PPCP",
    gradeName: "rPPCP",
    categoryId: "cat-recycled",
    description: "Recycled polypropylene copolymer for impact applications.",
    applications: ["Recycled", "Impact Moulding"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-08-23T12:05:00.000Z",
    updatedAt: "2026-09-04T09:20:00.000Z",
    createdBy: "Admin",
    updatedBy: "Admin",
    usage: used(1, 0, 1, 1, 0, 0),
  },
  {
    id: "GRD-1076",
    gradeCode: "R_PET",
    gradeName: "rPET",
    categoryId: "cat-recycled",
    description: "Recycled PET flakes / pellets for fibre and sheet.",
    applications: ["Fibre", "Sheet", "Recycled"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-08-24T07:50:00.000Z",
    updatedAt: "2026-09-09T07:30:00.000Z",
    createdBy: "Rahul Mehta",
    updatedBy: "Rahul Mehta",
    usage: used(6, 4, 8, 6, 5, 2),
  },
  {
    id: "GRD-1077",
    gradeCode: "R_PVC",
    gradeName: "rPVC",
    categoryId: "cat-recycled",
    description: "Recycled PVC for pipes, profiles and footwear compounds.",
    applications: ["Pipes", "Profiles", "Recycled"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-08-25T10:35:00.000Z",
    updatedAt: "2026-09-05T11:45:00.000Z",
    createdBy: "Priya Shah",
    updatedBy: "Admin",
    usage: used(2, 1, 2, 2, 1, 0),
  },
  {
    id: "GRD-1078",
    gradeCode: "R_ABS",
    gradeName: "rABS",
    categoryId: "cat-recycled",
    description: "Recycled ABS for non-critical injection moulding.",
    applications: ["Recycled", "Injection Moulding"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-08-26T08:20:00.000Z",
    updatedAt: "2026-09-03T14:15:00.000Z",
    createdBy: "Admin",
    updatedBy: "Admin",
    usage: used(2, 1, 2, 1, 1, 0),
  },
  {
    id: "GRD-1079",
    gradeCode: "RECYCLED_BASE_OIL",
    gradeName: "Recycled Base Oil",
    categoryId: "cat-base-oil",
    description: "Re-refined base oil for blending industrial lubricants.",
    applications: ["Lubricants", "Blending"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-08-27T11:55:00.000Z",
    updatedAt: "2026-09-08T16:00:00.000Z",
    createdBy: "Rahul Mehta",
    updatedBy: "Priya Shah",
    usage: used(3, 2, 3, 2, 2, 1),
  },
  {
    id: "GRD-1080",
    gradeCode: "BASE_OIL",
    gradeName: "Base Oil",
    categoryId: "cat-base-oil",
    description: "Virgin Group I / II base oil for lubricant blending.",
    applications: ["Lubricants", "Blending"],
    status: "ACTIVE",
    customerVisible: true,
    sellerVisible: true,
    createdAt: "2026-08-28T09:00:00.000Z",
    updatedAt: "2026-09-09T10:10:00.000Z",
    createdBy: "Priya Shah",
    updatedBy: "Admin",
    usage: used(4, 2, 4, 3, 3, 1),
  },
  {
    id: "GRD-1081",
    gradeCode: "NPA",
    gradeName: "NPA",
    categoryId: "cat-solvents",
    description: "n-Propyl alcohol for coatings, inks and pharmaceutical solvents.",
    applications: ["Coatings", "Pharma"],
    status: "INACTIVE",
    customerVisible: false,
    sellerVisible: true,
    createdAt: "2026-08-29T13:20:00.000Z",
    updatedAt: "2026-09-01T08:05:00.000Z",
    createdBy: "Admin",
    updatedBy: "Admin",
    usage: unused,
  },
  {
    id: "GRD-1082",
    gradeCode: "BAM",
    gradeName: "BAM",
    categoryId: "cat-chemicals",
    description: "Benzyl alcohol / related aromatic intermediate for coatings and fragrances.",
    applications: ["Coatings", "Fragrances"],
    status: "INACTIVE",
    customerVisible: false,
    sellerVisible: false,
    createdAt: "2026-08-30T10:40:00.000Z",
    updatedAt: "2026-09-02T09:50:00.000Z",
    createdBy: "Rahul Mehta",
    updatedBy: "Rahul Mehta",
    usage: unused,
  },
];

export const grades: Grade[] = hydrate(seeds);
