import type { KycRecord } from "@/types";

export const kycRecords: KycRecord[] = [
  {
    id: "KYC-881",
    entity: "Horizon Petrochem",
    entityType: "Customer",
    type: "GST",
    submitted: "2026-09-04T19:50:00+05:30",
    documents: 4,
    risk: "Medium",
    status: "Pending",
    reviewer: "Unassigned",
    gst: "29AAACH9988B1Z2",
    pan: "AAACH9988B",
    bank: "HDFC  ****4412",
    notes: "",
    source: "Customer App",
  },
  {
    id: "KYC-874",
    entity: "Sierra Films",
    entityType: "Customer",
    type: "Company",
    submitted: "2026-09-03T16:30:00+05:30",
    documents: 6,
    risk: "Low",
    status: "Under Review",
    reviewer: "Neha Kapoor",
    gst: "27AADCS2211D1Z3",
    pan: "AADCS2211D",
    bank: "ICICI ****9081",
    notes: "Waiting for board resolution.",
    source: "Customer App",
  },
  {
    id: "KYC-862",
    entity: "SkyHigh Logistics",
    entityType: "Seller",
    type: "Bank",
    submitted: "2026-09-04T18:50:00+05:30",
    documents: 3,
    risk: "Medium",
    status: "Under Review",
    reviewer: "Neha Kapoor",
    gst: "32AABCS3333C1Z7",
    pan: "AABCS3333C",
    bank: "SBI ****2209",
    notes: "Cancelled cheque mismatch.",
    source: "Seller Web",
  },
  {
    id: "KYC-851",
    entity: "Hygain Commodities",
    entityType: "Seller",
    type: "PAN",
    submitted: "2026-09-03T14:20:00+05:30",
    documents: 5,
    risk: "High",
    status: "Pending",
    reviewer: "Unassigned",
    gst: "24AABCH5555E1Z6",
    pan: "AABCH5555E",
    bank: "Axis ****1188",
    notes: "",
    source: "Seller App",
  },
  {
    id: "KYC-840",
    entity: "Apex Polymers Pvt Ltd",
    entityType: "Customer",
    type: "Company",
    submitted: "2026-01-09T10:00:00+05:30",
    documents: 8,
    risk: "Low",
    status: "Approved",
    reviewer: "Neha Kapoor",
    gst: "27AABCA1234A1Z5",
    pan: "AABCA1234A",
    bank: "HDFC ****1022",
    notes: "Verified against GSTN.",
    source: "Customer Web",
  },
  {
    id: "KYC-833",
    entity: "Northline Chemicals",
    entityType: "Customer",
    type: "GST",
    submitted: "2026-08-20T09:10:00+05:30",
    documents: 3,
    risk: "High",
    status: "Rejected",
    reviewer: "Amit Desai",
    gst: "07AAACN7788E1Z1",
    pan: "AAACN7788E",
    bank: "PNB ****3301",
    notes: "GSTIN inactive.",
    source: "Customer Web",
  },
  {
    id: "KYC-821",
    entity: "Vindhya Compounds",
    entityType: "Customer",
    type: "Company",
    submitted: "2026-02-12T11:00:00+05:30",
    documents: 7,
    risk: "Medium",
    status: "Expired",
    reviewer: "Neha Kapoor",
    gst: "24AAACV6677G1Z9",
    pan: "AAACV6677G",
    bank: "BOB ****7741",
    notes: "Annual re-KYC overdue.",
    source: "Customer Web",
  },
  {
    id: "KYC-810",
    entity: "Deccan Fuel Trading",
    entityType: "Seller",
    type: "Company",
    submitted: "2026-06-04T13:00:00+05:30",
    documents: 4,
    risk: "High",
    status: "Rejected",
    reviewer: "Neha Kapoor",
    gst: "36AABCD7777G1Z5",
    pan: "AABCD7777G",
    bank: "Yes ****0091",
    notes: "Beneficial ownership incomplete.",
    source: "Seller App",
  },
];
