import type { ProductGrade } from "@/types";

export const products: ProductGrade[] = [
  {
    id: "GRD-1001",
    grade: "PVC K67 ETHYLENE",
    commodity: "PVC",
    manufacturer: "Formosa",
    brand: "Formosa",
    specification: "K67, ethylene based, pipe grade",
    location: "Mundra",
    availableQty: 420,
    activeSellers: 6,
    activeOffers: 9,
    inventory: 420,
    status: "Active",
  },
  {
    id: "GRD-1002",
    grade: "PP RAFFIA",
    commodity: "PP",
    manufacturer: "Reliance",
    brand: "Relene",
    specification: "Raffia / woven sack, 3.5 MFI",
    location: "Hazira",
    availableQty: 860,
    activeSellers: 8,
    activeOffers: 14,
    inventory: 860,
    status: "Active",
  },
  {
    id: "GRD-1003",
    grade: "CHINA-HYGAIN HS1000R",
    commodity: "HDPE",
    manufacturer: "Hygain",
    brand: "Hygain",
    specification: "HS1000R blow moulding",
    location: "Nhava Sheva",
    availableQty: 210,
    activeSellers: 3,
    activeOffers: 4,
    inventory: 210,
    status: "Active",
  },
  {
    id: "GRD-1004",
    grade: "SCG P400S 3.5mfi",
    commodity: "PP",
    manufacturer: "SCG",
    brand: "SCG",
    specification: "P400S raffia 3.5 MFI",
    location: "Hazira",
    availableQty: 150,
    activeSellers: 2,
    activeOffers: 3,
    inventory: 150,
    status: "Active",
  },
  {
    id: "GRD-1005",
    grade: "PP FILM ORIENTAL PPF03 3mfi",
    commodity: "PP",
    manufacturer: "Oriental",
    brand: "Oriental",
    specification: "PPF03 film 3.0 MFI",
    location: "Noida",
    availableQty: 95,
    activeSellers: 2,
    activeOffers: 2,
    inventory: 95,
    status: "Active",
  },
  {
    id: "GRD-1006",
    grade: "ULSD Fuel",
    commodity: "Diesel",
    manufacturer: "IOCL",
    brand: "IOCL",
    specification: "Ultra low sulphur diesel",
    location: "Jamnagar",
    availableQty: 2400,
    activeSellers: 4,
    activeOffers: 5,
    inventory: 2400,
    status: "Active",
  },
  {
    id: "GRD-1007",
    grade: "Brent Crude",
    commodity: "Crude",
    manufacturer: "Spot",
    brand: "Brent",
    specification: "Dated Brent equivalent parcel",
    location: "Sikka",
    availableQty: 18,
    activeSellers: 1,
    activeOffers: 1,
    inventory: 18,
    status: "Inactive",
  },
  {
    id: "GRD-1008",
    grade: "Jet A1 Fuel",
    commodity: "Jet Fuel",
    manufacturer: "BPCL",
    brand: "BPCL",
    specification: "Jet A-1 aviation turbine fuel",
    location: "Kochi",
    availableQty: 320,
    activeSellers: 2,
    activeOffers: 2,
    inventory: 320,
    status: "Active",
  },
];
