import type { PushNotification } from "@/types/push-notification";

export const pushNotifications: PushNotification[] = [
  {
    id: "PSH-2401",
    name: "Monsoon Procurement Alert",
    title: "Monsoon bulk rates are live",
    body: "Lock in seasonal polymer pricing before depot tightness. Valid on HDPE and PP grades this week.",
    category: "PROMOTION",
    priority: "HIGH",
    platforms: ["CUSTOMER_APP", "CUSTOMER_WEB"],
    channels: ["PUSH", "IN_APP"],
    audienceMode: "SEGMENT",
    customerSegments: ["HIGH_VALUE_CUSTOMERS", "BUSINESS_CUSTOMERS"],
    sellerSegments: [],
    ctaText: "View offers",
    ctaAction: "OPEN_MARKETPLACE",
    deepLink: "/marketplace",
    status: "SENT",
    timezone: "Asia/Kolkata",
    scheduledDate: "2026-09-05",
    scheduledTime: "08:00",
    scheduledAt: "2026-09-05T02:30:00.000Z",
    sentAt: "2026-09-05T02:30:12.000Z",
    targeted: 974,
    delivered: 918,
    opened: 214,
    failed: 56,
    createdBy: "Admin User",
    createdAt: "2026-09-04T11:20:00+05:30",
    updatedAt: "2026-09-05T08:00:12+05:30",
  },
  {
    id: "PSH-2402",
    name: "Seller KYC Reminder",
    title: "Complete KYC to keep offers live",
    body: "Sellers with pending KYC will not appear in customer search after 20 Sept. Upload remaining documents today.",
    category: "KYC",
    priority: "HIGH",
    platforms: ["SELLER_APP", "SELLER_WEB"],
    channels: ["PUSH", "IN_APP"],
    audienceMode: "SEGMENT",
    customerSegments: [],
    sellerSegments: ["NEW_SELLERS"],
    ctaText: "Open documents",
    ctaAction: "OPEN_DOCUMENTS",
    deepLink: "/documents",
    status: "SENT",
    timezone: "Asia/Kolkata",
    scheduledDate: "2026-09-08",
    scheduledTime: "10:30",
    scheduledAt: "2026-09-08T05:00:00.000Z",
    sentAt: "2026-09-08T05:00:08.000Z",
    targeted: 58,
    delivered: 55,
    opened: 31,
    failed: 3,
    createdBy: "Neha Kapoor",
    createdAt: "2026-09-07T16:40:00+05:30",
    updatedAt: "2026-09-08T10:30:08+05:30",
  },
  {
    id: "PSH-2403",
    name: "GST Invoice Ready",
    title: "GST invoices for August are ready",
    body: "Download tax invoices from Documents. These files are required for monthly GST filing.",
    category: "DOCUMENT",
    priority: "NORMAL",
    platforms: ["CUSTOMER_WEB", "SELLER_WEB"],
    channels: ["IN_APP", "PUSH"],
    audienceMode: "ALL",
    customerSegments: ["ALL_CUSTOMERS"],
    sellerSegments: ["ALL_SELLERS"],
    ctaText: "Open documents",
    ctaAction: "OPEN_DOCUMENTS",
    status: "SENT",
    timezone: "Asia/Kolkata",
    scheduledDate: "2026-09-02",
    scheduledTime: "09:00",
    scheduledAt: "2026-09-02T03:30:00.000Z",
    sentAt: "2026-09-02T03:30:05.000Z",
    targeted: 2328,
    delivered: 2194,
    opened: 401,
    failed: 134,
    createdBy: "Amit Desai",
    createdAt: "2026-09-01T18:10:00+05:30",
    updatedAt: "2026-09-02T09:00:05+05:30",
  },
  {
    id: "PSH-2404",
    name: "Festival Offer Teaser",
    title: "Navratri procurement window opens 22 Sept",
    body: "Early-access pricing on PVC and PP raffia grades. Set reminders so your team does not miss the window.",
    category: "OFFER",
    priority: "NORMAL",
    platforms: ["CUSTOMER_APP", "CUSTOMER_WEB"],
    channels: ["PUSH", "IN_APP"],
    audienceMode: "ALL",
    customerSegments: ["ALL_CUSTOMERS"],
    sellerSegments: [],
    ctaText: "Browse marketplace",
    ctaAction: "OPEN_MARKETPLACE",
    deepLink: "/marketplace",
    status: "SCHEDULED",
    timezone: "Asia/Kolkata",
    scheduledDate: "2026-09-22",
    scheduledTime: "07:30",
    scheduledAt: "2026-09-22T02:00:00.000Z",
    targeted: 1842,
    delivered: 0,
    opened: 0,
    failed: 0,
    createdBy: "Admin User",
    createdAt: "2026-09-09T12:15:00+05:30",
    updatedAt: "2026-09-09T12:15:00+05:30",
  },
  {
    id: "PSH-2405",
    name: "Dispatch Slot Reminder",
    title: "Book dispatch slots for confirmed POs",
    body: "Vehicle slots for 12–14 Sept are filling up. Confirm loading windows to avoid detention charges.",
    category: "ORDER",
    priority: "HIGH",
    platforms: ["SELLER_APP", "SELLER_WEB"],
    channels: ["PUSH", "IN_APP"],
    audienceMode: "SEGMENT",
    customerSegments: [],
    sellerSegments: ["SELLERS_WITH_ACTIVE_OFFERS"],
    ctaText: "Open dispatch",
    ctaAction: "OPEN_DISPATCH",
    deepLink: "/dispatch",
    status: "SCHEDULED",
    timezone: "Asia/Kolkata",
    scheduledDate: "2026-09-11",
    scheduledTime: "08:00",
    scheduledAt: "2026-09-11T02:30:00.000Z",
    targeted: 167,
    delivered: 0,
    opened: 0,
    failed: 0,
    createdBy: "Admin User",
    createdAt: "2026-09-10T09:40:00+05:30",
    updatedAt: "2026-09-10T09:40:00+05:30",
  },
  {
    id: "PSH-2406",
    name: "Credit Limit Nudge",
    title: "Credit application still in draft",
    body: "Finish your PetroTrade credit application to unlock net-payment terms on verified grades.",
    category: "PAYMENT",
    priority: "NORMAL",
    platforms: ["CUSTOMER_APP"],
    channels: ["PUSH", "IN_APP"],
    audienceMode: "SEGMENT",
    customerSegments: ["NEW_CUSTOMERS"],
    sellerSegments: [],
    ctaText: "Continue application",
    ctaAction: "OPEN_CREDIT",
    deepLink: "/payments/credit",
    status: "DRAFT",
    timezone: "Asia/Kolkata",
    scheduledDate: "",
    scheduledTime: "10:00",
    targeted: 214,
    delivered: 0,
    opened: 0,
    failed: 0,
    createdBy: "Admin User",
    createdAt: "2026-09-10T11:05:00+05:30",
    updatedAt: "2026-09-10T11:05:00+05:30",
  },
  {
    id: "PSH-2407",
    name: "Maintenance Window",
    title: "Scheduled marketplace maintenance",
    body: "Customer and Seller portals will pause briefly on 12 Sept, 01:00–01:40 am IST. Orders already placed are not affected.",
    category: "SYSTEM",
    priority: "LOW",
    platforms: ["CUSTOMER_APP", "CUSTOMER_WEB", "SELLER_APP", "SELLER_WEB"],
    channels: ["IN_APP"],
    audienceMode: "ALL",
    customerSegments: ["ALL_CUSTOMERS"],
    sellerSegments: ["ALL_SELLERS"],
    ctaText: "Go to dashboard",
    ctaAction: "OPEN_DASHBOARD",
    status: "DRAFT",
    timezone: "Asia/Kolkata",
    scheduledDate: "2026-09-11",
    scheduledTime: "18:00",
    targeted: 2328,
    delivered: 0,
    opened: 0,
    failed: 0,
    createdBy: "Admin User",
    createdAt: "2026-09-10T14:22:00+05:30",
    updatedAt: "2026-09-10T14:22:00+05:30",
  },
  {
    id: "PSH-2408",
    name: "Failed Settlement Ping",
    title: "Settlement release delayed",
    body: "A settlement batch could not be pushed to the bank. Finance has been notified. Retry is scheduled automatically.",
    category: "PAYMENT",
    priority: "HIGH",
    platforms: ["SELLER_APP"],
    channels: ["PUSH"],
    audienceMode: "SEGMENT",
    customerSegments: [],
    sellerSegments: ["HIGH_PERFORMING_SELLERS"],
    ctaText: "View settlements",
    ctaAction: "OPEN_SETTLEMENTS",
    deepLink: "/settlements",
    status: "FAILED",
    timezone: "Asia/Kolkata",
    scheduledDate: "2026-09-06",
    scheduledTime: "16:15",
    scheduledAt: "2026-09-06T10:45:00.000Z",
    sentAt: "2026-09-06T10:45:20.000Z",
    targeted: 94,
    delivered: 0,
    opened: 0,
    failed: 94,
    createdBy: "Amit Desai",
    createdAt: "2026-09-06T16:10:00+05:30",
    updatedAt: "2026-09-06T16:15:20+05:30",
  },
];
