import type { Shipment } from "@/types";

export const shipments: Shipment[] = [
  {
    id: "SHP-4412",
    orderId: "PT-9021",
    seller: "Oriental Polymers",
    customer: "Apex Polymers Pvt Ltd",
    grade: "PP RAFFIA",
    quantity: 48,
    vehicle: "MH-04-BX-2211",
    route: "Noida → Mumbai",
    eta: "2026-09-07T18:00:00+05:30",
    status: "Scheduled",
    milestone: "Vehicle assigned",
    source: "Seller Web",
  },
  {
    id: "SHP-4401",
    orderId: "PT-9011",
    seller: "Global Energy Ltd.",
    customer: "Coastal Resins",
    grade: "ULSD Fuel",
    quantity: 80,
    vehicle: "GJ-10-FT-9088",
    route: "Jamnagar → Chennai",
    eta: "2026-09-06T14:00:00+05:30",
    status: "In Transit",
    milestone: "Crossed Ankleshwar checkpoint",
    source: "Seller App",
  },
  {
    id: "SHP-4388",
    orderId: "PT-8992",
    seller: "Oriental Polymers",
    customer: "Apex Polymers Pvt Ltd",
    grade: "PP FILM ORIENTAL PPF03 3mfi",
    quantity: 20,
    vehicle: "UP-16-QT-4410",
    route: "Noida → Mumbai",
    eta: "2026-08-30T11:00:00+05:30",
    status: "Delivered",
    milestone: "POD captured",
    source: "Seller Web",
  },
  {
    id: "SHP-4370",
    orderId: "PT-8974",
    seller: "Desert Sands Crude",
    customer: "Delta Packaging Mills",
    grade: "Brent Crude",
    quantity: 4,
    vehicle: "GJ-03-CR-1102",
    route: "Sikka → Gurugram",
    eta: "2026-08-26T20:00:00+05:30",
    status: "Delayed",
    milestone: "Hold at depot — documentation",
    source: "Admin Portal",
  },
  {
    id: "SHP-4419",
    orderId: "PT-8966",
    seller: "Oriental Polymers",
    customer: "Eastern Pipe Works",
    grade: "PVC K67 ETHYLENE",
    quantity: 36,
    vehicle: "MH-12-LD-7733",
    route: "Mundra → Kolkata",
    eta: "2026-09-08T09:00:00+05:30",
    status: "Loading",
    milestone: "Loading bay 3",
    source: "Seller Web",
  },
  {
    id: "SHP-4422",
    orderId: "PT-9018",
    seller: "SCG Petrochem India",
    customer: "Delta Packaging Mills",
    grade: "SCG P400S 3.5mfi",
    quantity: 60,
    vehicle: "GJ-16-SC-2209",
    route: "Hazira → Gurugram",
    eta: "2026-09-09T16:00:00+05:30",
    status: "Dispatched",
    milestone: "Gate out",
    source: "Seller App",
  },
];
